### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by duygupotur** [zekiahmetbayar/Valf#10]
- [x] daha önce ssh kullanılmamış makinede .ssh, config gibi dosyalar eksik olabilir. valf'ı ilk defa kullanırken bunların kontrolü ve oluşturulması
- [x] Linux sertifika yapısının incelenmesi (ssh-keygen, ssh-copy-id, ~/.ssh/known_hosts, ~/.ssh/authorized_keys)
- [x] bir makineye ilk defa bağlanılıyorsa fingerrpint ekleme sorusunun yakalanması, yeni bir dialog üzerinde yes/no seçeneğinin sorulması
- [x] bağlanmak istenen ip adresini farklı bir makine aldıysa known değiştiğiyle ilgili uyarı verilmes, known_hosts düzenlenmesinin sorulması

**Comment by duygupotur** [comment]
- [x] config dosyası yoksa hata veriyor
![image](https://user-images.githubusercontent.com/11041014/91125051-754c0800-e6a9-11ea-8453-6d091580372f.png)

**Comment by zekiahmetbayar** [comment]
- [x] SSH dizinleri ana makinede yoksa oluşturulması
- [x] YES/NO sorusunun butonlar haline getirilmesi
- [x] Host identify hatası penceresinde . karakterinin kaldırılması
- [x] Host identify hatası alınmasına rağmen notebook'un açılması
- [x] Host identify hata penceresinden cümlenin lowercase alınması 
- [x] Paramiko SFTP kütüphanesinin incelenmesi
- [x] Lokal ve host makinelerin dosya dizinlerinde gezinilecek bir yapı kurulması
